from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from genesys_memory.models.enums import EdgeType, MemoryStatus
from genesys_memory.models.node import MemoryNode
from genesys_memory.models.edge import MemoryEdge


class GraphStorageProvider(Protocol):
    async def initialize(self, user_id: str) -> None: ...
    async def destroy(self, user_id: str) -> None: ...

    async def create_node(self, node: MemoryNode) -> str: ...
    async def get_node(self, node_id: str) -> MemoryNode | None: ...
    async def update_node(self, node_id: str, updates: dict[str, Any]) -> None: ...
    async def delete_node(self, node_id: str) -> None: ...
    async def get_nodes_by_status(self, status: MemoryStatus, limit: int = 100) -> list[MemoryNode]: ...

    async def create_edge(self, edge: MemoryEdge) -> str: ...
    async def get_edges(self, node_id: str, direction: str, edge_type: EdgeType | None = None) -> list[MemoryEdge]: ...
    async def update_edge_weight(self, edge_id: str, weight: float) -> None: ...
    async def validate_edge(self, edge_id: str) -> None: ...
    async def delete_edge(self, edge_id: str) -> None: ...
    async def get_all_edges(self, node_ids: list[str] | None = None) -> list[MemoryEdge]: ...
    async def edge_exists(self, source_id: str, target_id: str, edge_type: EdgeType) -> bool: ...

    async def traverse(self, start_id: str, depth: int, edge_types: list[EdgeType] | None = None, org_ids: list[str] | None = None) -> list[MemoryNode]: ...
    async def get_causal_chain(self, node_id: str, direction: str, org_ids: list[str] | None = None) -> list[MemoryNode]: ...
    async def get_causal_weight(self, node_id: str) -> int: ...
    async def get_degree(self, node_id: str) -> int: ...
    async def get_supportive_degree(self, node_id: str) -> int: ...
    async def is_orphan(self, node_id: str) -> bool: ...
    async def get_orphans(self) -> list[MemoryNode]: ...

    async def vector_search(self, embedding: list[float], k: int = 10, status_filter: list[MemoryStatus] | None = None, org_ids: list[str] | None = None) -> list[tuple[MemoryNode, float]]: ...
    async def keyword_search(self, query: str, entity_refs: list[str] | None = None, k: int = 10, org_ids: list[str] | None = None) -> list[MemoryNode]: ...
    async def get_stats(self) -> dict[str, Any]: ...

    async def promote_to_org(self, node_id: str, org_id: str) -> None: ...


class EmbeddingProvider(Protocol):
    async def embed(self, text: str) -> list[float]: ...
    async def embed_batch(self, texts: list[str]) -> list[list[float]]: ...

    @property
    def dimension(self) -> int: ...


class CacheProvider(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl_seconds: int = 300) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...


class LLMProvider(Protocol):
    async def consolidate(self, episodic_memories: list[str]) -> str: ...
    async def detect_contradiction(self, memory_a: str, memory_b: str) -> tuple[bool, float, str | None]: ...
    async def infer_causal_edges(self, new_memory: str, existing_memories: list[tuple[str, str]]) -> list[tuple[str, EdgeType, float, str | None]]: ...
    async def extract_entities(self, text: str) -> list[str]: ...
    async def generate_summary(self, text: str) -> str: ...
    async def classify_category(self, text: str) -> str | None: ...


class EventBusProvider(Protocol):
    async def publish(self, channel: str, payload: dict[str, Any]) -> None: ...
    async def subscribe(self, channel: str, handler: Callable[..., Any]) -> None: ...
